name: unit test
on:
  push:
    branches:
    - main
    - feature/*
jobs:
  run_test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: npm test
      run: npm test
